(assert (Usuario (id u1)))
(assert (Posee_Plataforma (usuario u1) (plataforma "PC")))
(assert (Posee_Plataforma (usuario u1) (plataforma "PS4")))
(assert (Prefiere_Genero (usuario u1) (genero "RPG")))
(assert (Prefiere_Genero (usuario u1) (genero "Aventura")))
(assert (No_Gusta_Genero (usuario u1) (genero "Terror")))
(assert (Prefiere_Complejidad (usuario u1) (nivel "Alta")))
(assert (Prefiere_Duracion (usuario u1) (tipo "Larga")))
(assert (Prefiere_Multiplayer (usuario u1) (tipo "Si")))
(assert (Edad_Usuario (usuario u1) (edad 17)))
(assert (Gusto_Juego (usuario u1) (juego g1)))
(assert (Jugo_Juego (usuario u1) (juego g1)))

(assert (Usuario (id u2)))
(assert (Posee_Plataforma (usuario u2) (plataforma "PC")))
(assert (Posee_Plataforma (usuario u2) (plataforma "Xbox One")))
(assert (Prefiere_Genero (usuario u2) (genero "RPG")))
(assert (Prefiere_Genero (usuario u2) (genero "Acción")))
(assert (No_Gusta_Genero (usuario u2) (genero "Terror")))
(assert (Prefiere_Complejidad (usuario u2) (nivel "Media")))
(assert (Prefiere_Duracion (usuario u2) (tipo "Corta")))
(assert (Prefiere_Multiplayer (usuario u2) (tipo "No")))
(assert (Edad_Usuario (usuario u2) (edad 19)))
(assert (Gusto_Juego (usuario u2) (juego g2)))
(assert (Jugo_Juego (usuario u2) (juego g2)))

(assert (Usuario (id u3)))
(assert (Posee_Plataforma (usuario u3) (plataforma "PC")))
(assert (Posee_Plataforma (usuario u3) (plataforma "PS4")))
(assert (Prefiere_Genero (usuario u3) (genero "Aventura")))
(assert (Prefiere_Genero (usuario u3) (genero "Deportes")))
(assert (No_Gusta_Genero (usuario u3) (genero "Terror")))
(assert (Prefiere_Complejidad (usuario u3) (nivel "Baja")))
(assert (Prefiere_Duracion (usuario u3) (tipo "Media")))
(assert (Prefiere_Multiplayer (usuario u3) (tipo "No")))
(assert (Edad_Usuario (usuario u3) (edad 30)))
(assert (Gusto_Juego (usuario u3) (juego g3)))
(assert (Jugo_Juego (usuario u3) (juego g3)))

(assert (Usuario (id u4)))
(assert (Posee_Plataforma (usuario u4) (plataforma "PS4")))
(assert (Posee_Plataforma (usuario u4) (plataforma "Xbox One")))
(assert (Prefiere_Genero (usuario u4) (genero "Terror")))
(assert (Prefiere_Genero (usuario u4) (genero "Acción")))
(assert (No_Gusta_Genero (usuario u4) (genero "RPG")))
(assert (Prefiere_Complejidad (usuario u4) (nivel "Alta")))
(assert (Prefiere_Duracion (usuario u4) (tipo "Larga")))
(assert (Prefiere_Multiplayer (usuario u4) (tipo "Si")))
(assert (Edad_Usuario (usuario u4) (edad 22)))
(assert (Gusto_Juego (usuario u4) (juego g4)))
(assert (Jugo_Juego (usuario u4) (juego g4)))

(assert (Usuario (id u5)))
(assert (Posee_Plataforma (usuario u5) (plataforma "PC")))
(assert (Posee_Plataforma (usuario u5) (plataforma "PS4")))
(assert (Prefiere_Genero (usuario u5) (genero "Aventura")))
(assert (Prefiere_Genero (usuario u5) (genero "RPG")))
(assert (No_Gusta_Genero (usuario u5) (genero "Deportes")))
(assert (Prefiere_Complejidad (usuario u5) (nivel "Media")))
(assert (Prefiere_Duracion (usuario u5) (tipo "Corta")))
(assert (Prefiere_Multiplayer (usuario u5) (tipo "No")))
(assert (Edad_Usuario (usuario u5) (edad 28)))
(assert (Gusto_Juego (usuario u5) (juego g5)))
(assert (Jugo_Juego (usuario u5) (juego g5)))

(assert (Juego (id g1)))
(assert (Titulo_Juego (juego g1) (titulo "Dragon Quest XI")))
(assert (Tiene_Genero (juego g1) (genero "RPG")))
(assert (Disponible_En (juego g1) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g1) (nivel "Alta")))
(assert (Tiene_Duracion (juego g1) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g1) (tipo "No")))
(assert (Clasificacion_Edad (juego g1) (clasificacion "13+")))

(assert (Juego (id g2)))
(assert (Titulo_Juego (juego g2) (titulo "Persona 5")))
(assert (Tiene_Genero (juego g2) (genero "RPG")))
(assert (Disponible_En (juego g2) (plataforma "PS4")))
(assert (Tiene_Complejidad (juego g2) (nivel "Alta")))
(assert (Tiene_Duracion (juego g2) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g2) (tipo "No")))
(assert (Clasificacion_Edad (juego g2) (clasificacion "16+")))
(assert (Similar_A (juego1 g2) (juego2 g1)))

(assert (Juego (id g3)))
(assert (Titulo_Juego (juego g3) (titulo "Silent Hill")))
(assert (Tiene_Genero (juego g3) (genero "Terror")))
(assert (Disponible_En (juego g3) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g3) (nivel "Media")))
(assert (Tiene_Duracion (juego g3) (tipo "Corta")))
(assert (Tiene_Multiplayer (juego g3) (tipo "No")))
(assert (Clasificacion_Edad (juego g3) (clasificacion "18+")))

(assert (Juego (id g4)))
(assert (Titulo_Juego (juego g4) (titulo "Monster Hunter World")))
(assert (Tiene_Genero (juego g4) (genero "Aventura")))
(assert (Disponible_En (juego g4) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g4) (nivel "Alta")))
(assert (Tiene_Duracion (juego g4) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g4) (tipo "Si")))
(assert (Clasificacion_Edad (juego g4) (clasificacion "13+")))

(assert (Juego (id g5)))
(assert (Titulo_Juego (juego g5) (titulo "The Witcher 3: Wild Hunt")))
(assert (Tiene_Genero (juego g5) (genero "RPG")))
(assert (Disponible_En (juego g5) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g5) (nivel "Alta")))
(assert (Tiene_Duracion (juego g5) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g5) (tipo "No")))
(assert (Clasificacion_Edad (juego g5) (clasificacion "18+")))

(assert (Juego (id g6)))
(assert (Titulo_Juego (juego g6) (titulo "Dark Souls III")))
(assert (Tiene_Genero (juego g6) (genero "Acción")))
(assert (Disponible_En (juego g6) (plataforma "PS4")))
(assert (Tiene_Complejidad (juego g6) (nivel "Alta")))
(assert (Tiene_Duracion (juego g6) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g6) (tipo "No")))
(assert (Clasificacion_Edad (juego g6) (clasificacion "16+")))

(assert (Juego (id g7)))
(assert (Titulo_Juego (juego g7) (titulo "The Last of Us Part II")))
(assert (Tiene_Genero (juego g7) (genero "Acción")))
(assert (Disponible_En (juego g7) (plataforma "PS4")))
(assert (Tiene_Complejidad (juego g7) (nivel "Alta")))
(assert (Tiene_Duracion (juego g7) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g7) (tipo "No")))
(assert (Clasificacion_Edad (juego g7) (clasificacion "18+")))

(assert (Juego (id g8)))
(assert (Titulo_Juego (juego g8) (titulo "Red Dead Redemption 2")))
(assert (Tiene_Genero (juego g8) (genero "Aventura")))
(assert (Disponible_En (juego g8) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g8) (nivel "Alta")))
(assert (Tiene_Duracion (juego g8) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g8) (tipo "Si")))
(assert (Clasificacion_Edad (juego g8) (clasificacion "18+")))

(assert (Juego (id g9)))
(assert (Titulo_Juego (juego g9) (titulo "Apex Legends")))
(assert (Tiene_Genero (juego g9) (genero "Acción")))
(assert (Disponible_En (juego g9) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g9) (nivel "Media")))
(assert (Tiene_Duracion (juego g9) (tipo "Media")))
(assert (Tiene_Multiplayer (juego g9) (tipo "Si")))
(assert (Clasificacion_Edad (juego g9) (clasificacion "13+")))

(assert (Juego (id g10)))
(assert (Titulo_Juego (juego g10) (titulo "Overwatch")))
(assert (Tiene_Genero (juego g10) (genero "Acción")))
(assert (Disponible_En (juego g10) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g10) (nivel "Media")))
(assert (Tiene_Duracion (juego g10) (tipo "Media")))
(assert (Tiene_Multiplayer (juego g10) (tipo "Si")))
(assert (Clasificacion_Edad (juego g10) (clasificacion "12+")))

(assert (Juego (id g11)))
(assert (Titulo_Juego (juego g11) (titulo "Minecraft")))
(assert (Tiene_Genero (juego g11) (genero "Aventura")))
(assert (Disponible_En (juego g11) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g11) (nivel "Baja")))
(assert (Tiene_Duracion (juego g11) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g11) (tipo "Si")))
(assert (Clasificacion_Edad (juego g11) (clasificacion "7+")))

(assert (Juego (id g12)))
(assert (Titulo_Juego (juego g12) (titulo "Fortnite")))
(assert (Tiene_Genero (juego g12) (genero "Acción")))
(assert (Disponible_En (juego g12) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g12) (nivel "Media")))
(assert (Tiene_Duracion (juego g12) (tipo "Corta")))
(assert (Tiene_Multiplayer (juego g12) (tipo "Si")))
(assert (Clasificacion_Edad (juego g12) (clasificacion "13+")))

(assert (Juego (id g13)))
(assert (Titulo_Juego (juego g13) (titulo "GTA V")))
(assert (Tiene_Genero (juego g13) (genero "Aventura")))
(assert (Disponible_En (juego g13) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g13) (nivel "Alta")))
(assert (Tiene_Duracion (juego g13) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g13) (tipo "Si")))
(assert (Clasificacion_Edad (juego g13) (clasificacion "18+")))

(assert (Juego (id g14)))
(assert (Titulo_Juego (juego g14) (titulo "Call of Duty: Warzone")))
(assert (Tiene_Genero (juego g14) (genero "Acción")))
(assert (Disponible_En (juego g14) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g14) (nivel "Alta")))
(assert (Tiene_Duracion (juego g14) (tipo "Corta")))
(assert (Tiene_Multiplayer (juego g14) (tipo "Si")))
(assert (Clasificacion_Edad (juego g14) (clasificacion "18+")))

(assert (Juego (id g15)))
(assert (Titulo_Juego (juego g15) (titulo "Assassin's Creed Odyssey")))
(assert (Tiene_Genero (juego g15) (genero "Aventura")))
(assert (Disponible_En (juego g15) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g15) (nivel "Alta")))
(assert (Tiene_Duracion (juego g15) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g15) (tipo "No")))
(assert (Clasificacion_Edad (juego g15) (clasificacion "18+")))

(assert (Juego (id g16)))
(assert (Titulo_Juego (juego g16) (titulo "Cyberpunk 2077")))
(assert (Tiene_Genero (juego g16) (genero "RPG")))
(assert (Disponible_En (juego g16) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g16) (nivel "Alta")))
(assert (Tiene_Duracion (juego g16) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g16) (tipo "No")))
(assert (Clasificacion_Edad (juego g16) (clasificacion "18+")))

(assert (Juego (id g17)))
(assert (Titulo_Juego (juego g17) (titulo "Horizon Zero Dawn")))
(assert (Tiene_Genero (juego g17) (genero "Aventura")))
(assert (Disponible_En (juego g17) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g17) (nivel "Alta")))
(assert (Tiene_Duracion (juego g17) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g17) (tipo "No")))
(assert (Clasificacion_Edad (juego g17) (clasificacion "16+")))

(assert (Juego (id g18)))
(assert (Titulo_Juego (juego g18) (titulo "Sekiro: Shadows Die Twice")))
(assert (Tiene_Genero (juego g18) (genero "Acción")))
(assert (Disponible_En (juego g18) (plataforma "PS4")))
(assert (Tiene_Complejidad (juego g18) (nivel "Alta")))
(assert (Tiene_Duracion (juego g18) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g18) (tipo "No")))
(assert (Clasificacion_Edad (juego g18) (clasificacion "18+")))

(assert (Juego (id g19)))
(assert (Titulo_Juego (juego g19) (titulo "Fortnite")))
(assert (Tiene_Genero (juego g19) (genero "Acción")))
(assert (Disponible_En (juego g19) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g19) (nivel "Baja")))
(assert (Tiene_Duracion (juego g19) (tipo "Corta")))
(assert (Tiene_Multiplayer (juego g19) (tipo "Si")))
(assert (Clasificacion_Edad (juego g19) (clasificacion "12+")))

(assert (Juego (id g20)))
(assert (Titulo_Juego (juego g20) (titulo "World of Warcraft")))
(assert (Tiene_Genero (juego g20) (genero "RPG")))
(assert (Disponible_En (juego g20) (plataforma "PC")))
(assert (Tiene_Complejidad (juego g20) (nivel "Alta")))
(assert (Tiene_Duracion (juego g20) (tipo "Larga")))
(assert (Tiene_Multiplayer (juego g20) (tipo "Si")))
(assert (Clasificacion_Edad (juego g20) (clasificacion "12+")))

